[build]
  command = "npm run build"
  publish = ".next"

[dev]
  # Allows `netlify dev` to run Next.js locally
  command = "npm run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
